version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.18"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  
