[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rtdocs"
authors = [{name = "Tai Xin Lian", email = "sirchanmp@zohomail.cn"}]
dynamic = ["version", "description"]
